[package]
name = "scx_oreore"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-only"
publish = false

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
ctrlc = { version = "3", features = ["termination"] }
libbpf-rs = "=0.26.2"
scx_utils = "=1.1.3"

[build-dependencies]
scx_cargo = "=1.1.3"

[workspace]
resolver = "2"
